context:
  name: awkward-cpp
  version: 22

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-cpp-{{ version }}.tar.gz
  sha256: 21679636fb21cfe3715f88a32326a579199384db2da4a62995c310502d7fe85f

build:
  number: 0

requirements:
  build:
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): pybind11
    - "{{ compiler('cxx') }}"
    - cmake >=3.15
    - pip
    - scikit-build-core >=0.1.3
  host:
    - python
    - pybind11
  run:
    - python
    - importlib-resources
    - numpy >=1.18.0

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77

  emscripten_tests:
    python:
      pytest_files:
      - test_import_awkward_cpp.py
