context:
  name: awkward-cpp
  version: 12

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-cpp-{{ version }}.tar.gz
  sha256: 429f7fcc37a671afa67fe9680f2edc3a123d1c74d399e5889c654f9529f9f8f2

build:
  number: 0

requirements:
  build:
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): pybind11
    - "{{ compiler('cxx') }}"
    - cmake >=3.15
    - scikit-build-core >=0.1.3
    - make
    - pip
  host:
    - python
    - pybind11
  run:
    - python
    - importlib-resources
    - numpy >=1.17.0

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt
    - rapidjson/bin/jsonschema/LICENSE

extra:
  recipe-maintainers:
    - agoose77
